#!/usr/bin/env python3
"""Flatten captured Liquid Glass tiles to opaque sRGB and build a family-grouped contact sheet."""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
import os, shutil, subprocess, sys

OUT_DIR = Path("Marketing/icon")
BG = (0xFA, 0xF4, 0xED)
INK = (0x57, 0x52, 0x79)
# family label → variant slugs (order = sheet order). Tiles not listed land in "More".
FAMILIES = {
    "Aurora": ['aurora-bloom', 'aurora-dusk', 'aurora-veil', 'aurora-prism'],
    "Jewel": ['sapphire-glass', 'emerald-glass', 'amethyst-glass', 'topaz-glass', 'ruby-glass'],
    "Midnight": ['obsidian', 'midnight-bloom', 'deep-well'],
    "Frost / light": ['frost-clear', 'pearl-opal', 'liquid-aero'],
    "Warm": ['gold-amber'],
    "Copper": ['copper-bloom', 'copper-veil', 'copper-lens', 'copper-ember', 'copper-gold', 'copper-rose', 'copper-prism', 'copper-deep', 'copper-glow', 'copper-frost'],
    "Lens": ['prism-caustic', 'gem-cut'],
    "Glass": ['glass-crimson', 'glass-coral', 'glass-tangerine', 'glass-amber', 'glass-honey', 'glass-citron', 'glass-lime', 'glass-jade', 'glass-mint', 'glass-aqua', 'glass-cyan', 'glass-sky', 'glass-azure', 'glass-cobalt', 'glass-indigo', 'glass-violet', 'glass-orchid', 'glass-magenta', 'glass-rose', 'glass-blush'],
    "Glass d1": ['glass-crimson-d1', 'glass-coral-d1', 'glass-tangerine-d1', 'glass-amber-d1', 'glass-honey-d1', 'glass-citron-d1', 'glass-lime-d1', 'glass-jade-d1', 'glass-mint-d1', 'glass-aqua-d1', 'glass-cyan-d1', 'glass-sky-d1', 'glass-azure-d1', 'glass-cobalt-d1', 'glass-indigo-d1', 'glass-violet-d1', 'glass-orchid-d1', 'glass-magenta-d1', 'glass-rose-d1', 'glass-blush-d1'],
    "Glass d2": ['glass-crimson-d2', 'glass-coral-d2', 'glass-tangerine-d2', 'glass-amber-d2', 'glass-honey-d2', 'glass-citron-d2', 'glass-lime-d2', 'glass-jade-d2', 'glass-mint-d2', 'glass-aqua-d2', 'glass-cyan-d2', 'glass-sky-d2', 'glass-azure-d2', 'glass-cobalt-d2', 'glass-indigo-d2', 'glass-violet-d2', 'glass-orchid-d2', 'glass-magenta-d2', 'glass-rose-d2', 'glass-blush-d2'],
    "Glass d3": ['glass-crimson-d3', 'glass-coral-d3', 'glass-tangerine-d3', 'glass-amber-d3', 'glass-honey-d3', 'glass-citron-d3', 'glass-lime-d3', 'glass-jade-d3', 'glass-mint-d3', 'glass-aqua-d3', 'glass-cyan-d3', 'glass-sky-d3', 'glass-azure-d3', 'glass-cobalt-d3', 'glass-indigo-d3', 'glass-violet-d3', 'glass-orchid-d3', 'glass-magenta-d3', 'glass-rose-d3', 'glass-blush-d3'],
    "Glass t1": ['glass-crimson-t1', 'glass-crimson-t1-s1', 'glass-coral-t1', 'glass-coral-t1-s1', 'glass-tangerine-t1', 'glass-tangerine-t1-s1', 'glass-amber-t1', 'glass-amber-t1-s1', 'glass-honey-t1', 'glass-honey-t1-s1', 'glass-citron-t1', 'glass-citron-t1-s1', 'glass-lime-t1', 'glass-lime-t1-s1', 'glass-jade-t1', 'glass-jade-t1-s1', 'glass-mint-t1', 'glass-mint-t1-s1', 'glass-aqua-t1', 'glass-aqua-t1-s1', 'glass-cyan-t1', 'glass-cyan-t1-s1', 'glass-sky-t1', 'glass-sky-t1-s1', 'glass-azure-t1', 'glass-azure-t1-s1', 'glass-cobalt-t1', 'glass-cobalt-t1-s1', 'glass-indigo-t1', 'glass-indigo-t1-s1', 'glass-violet-t1', 'glass-violet-t1-s1', 'glass-orchid-t1', 'glass-orchid-t1-s1', 'glass-magenta-t1', 'glass-magenta-t1-s1', 'glass-rose-t1', 'glass-rose-t1-s1', 'glass-blush-t1', 'glass-blush-t1-s1'],
    "Glass t2": ['glass-crimson-t2', 'glass-crimson-t2-s1', 'glass-coral-t2', 'glass-coral-t2-s1', 'glass-tangerine-t2', 'glass-tangerine-t2-s1', 'glass-amber-t2', 'glass-amber-t2-s1', 'glass-honey-t2', 'glass-honey-t2-s1', 'glass-citron-t2', 'glass-citron-t2-s1', 'glass-lime-t2', 'glass-lime-t2-s1', 'glass-jade-t2', 'glass-jade-t2-s1', 'glass-mint-t2', 'glass-mint-t2-s1', 'glass-aqua-t2', 'glass-aqua-t2-s1', 'glass-cyan-t2', 'glass-cyan-t2-s1', 'glass-sky-t2', 'glass-sky-t2-s1', 'glass-azure-t2', 'glass-azure-t2-s1', 'glass-cobalt-t2', 'glass-cobalt-t2-s1', 'glass-indigo-t2', 'glass-indigo-t2-s1', 'glass-violet-t2', 'glass-violet-t2-s1', 'glass-orchid-t2', 'glass-orchid-t2-s1', 'glass-magenta-t2', 'glass-magenta-t2-s1', 'glass-rose-t2', 'glass-rose-t2-s1', 'glass-blush-t2', 'glass-blush-t2-s1'],
    "Glass t3": ['glass-crimson-t3', 'glass-crimson-t3-s1', 'glass-coral-t3', 'glass-coral-t3-s1', 'glass-tangerine-t3', 'glass-tangerine-t3-s1', 'glass-amber-t3', 'glass-amber-t3-s1', 'glass-honey-t3', 'glass-honey-t3-s1', 'glass-citron-t3', 'glass-citron-t3-s1', 'glass-lime-t3', 'glass-lime-t3-s1', 'glass-jade-t3', 'glass-jade-t3-s1', 'glass-mint-t3', 'glass-mint-t3-s1', 'glass-aqua-t3', 'glass-aqua-t3-s1', 'glass-cyan-t3', 'glass-cyan-t3-s1', 'glass-sky-t3', 'glass-sky-t3-s1', 'glass-azure-t3', 'glass-azure-t3-s1', 'glass-cobalt-t3', 'glass-cobalt-t3-s1', 'glass-indigo-t3', 'glass-indigo-t3-s1', 'glass-violet-t3', 'glass-violet-t3-s1', 'glass-orchid-t3', 'glass-orchid-t3-s1', 'glass-magenta-t3', 'glass-magenta-t3-s1', 'glass-rose-t3', 'glass-rose-t3-s1', 'glass-blush-t3', 'glass-blush-t3-s1'],
    "Glass Ring": ['glass-ring-crimson', 'glass-ring-coral', 'glass-ring-tangerine', 'glass-ring-amber', 'glass-ring-honey', 'glass-ring-citron', 'glass-ring-lime', 'glass-ring-jade', 'glass-ring-mint', 'glass-ring-aqua', 'glass-ring-cyan', 'glass-ring-sky', 'glass-ring-azure', 'glass-ring-cobalt', 'glass-ring-indigo', 'glass-ring-violet', 'glass-ring-orchid', 'glass-ring-magenta', 'glass-ring-rose', 'glass-ring-blush'],
    "Glass Ring d1": ['glass-ring-crimson-d1', 'glass-ring-coral-d1', 'glass-ring-tangerine-d1', 'glass-ring-amber-d1', 'glass-ring-honey-d1', 'glass-ring-citron-d1', 'glass-ring-lime-d1', 'glass-ring-jade-d1', 'glass-ring-mint-d1', 'glass-ring-aqua-d1', 'glass-ring-cyan-d1', 'glass-ring-sky-d1', 'glass-ring-azure-d1', 'glass-ring-cobalt-d1', 'glass-ring-indigo-d1', 'glass-ring-violet-d1', 'glass-ring-orchid-d1', 'glass-ring-magenta-d1', 'glass-ring-rose-d1', 'glass-ring-blush-d1'],
    "Glass Ring d2": ['glass-ring-crimson-d2', 'glass-ring-coral-d2', 'glass-ring-tangerine-d2', 'glass-ring-amber-d2', 'glass-ring-honey-d2', 'glass-ring-citron-d2', 'glass-ring-lime-d2', 'glass-ring-jade-d2', 'glass-ring-mint-d2', 'glass-ring-aqua-d2', 'glass-ring-cyan-d2', 'glass-ring-sky-d2', 'glass-ring-azure-d2', 'glass-ring-cobalt-d2', 'glass-ring-indigo-d2', 'glass-ring-violet-d2', 'glass-ring-orchid-d2', 'glass-ring-magenta-d2', 'glass-ring-rose-d2', 'glass-ring-blush-d2'],
    "Glass Ring d3": ['glass-ring-crimson-d3', 'glass-ring-coral-d3', 'glass-ring-tangerine-d3', 'glass-ring-amber-d3', 'glass-ring-honey-d3', 'glass-ring-citron-d3', 'glass-ring-lime-d3', 'glass-ring-jade-d3', 'glass-ring-mint-d3', 'glass-ring-aqua-d3', 'glass-ring-cyan-d3', 'glass-ring-sky-d3', 'glass-ring-azure-d3', 'glass-ring-cobalt-d3', 'glass-ring-indigo-d3', 'glass-ring-violet-d3', 'glass-ring-orchid-d3', 'glass-ring-magenta-d3', 'glass-ring-rose-d3', 'glass-ring-blush-d3'],
    "Glass Ring t1": ['glass-ring-crimson-t1', 'glass-ring-crimson-t1-s1', 'glass-ring-coral-t1', 'glass-ring-coral-t1-s1', 'glass-ring-tangerine-t1', 'glass-ring-tangerine-t1-s1', 'glass-ring-amber-t1', 'glass-ring-amber-t1-s1', 'glass-ring-honey-t1', 'glass-ring-honey-t1-s1', 'glass-ring-citron-t1', 'glass-ring-citron-t1-s1', 'glass-ring-lime-t1', 'glass-ring-lime-t1-s1', 'glass-ring-jade-t1', 'glass-ring-jade-t1-s1', 'glass-ring-mint-t1', 'glass-ring-mint-t1-s1', 'glass-ring-aqua-t1', 'glass-ring-aqua-t1-s1', 'glass-ring-cyan-t1', 'glass-ring-cyan-t1-s1', 'glass-ring-sky-t1', 'glass-ring-sky-t1-s1', 'glass-ring-azure-t1', 'glass-ring-azure-t1-s1', 'glass-ring-cobalt-t1', 'glass-ring-cobalt-t1-s1', 'glass-ring-indigo-t1', 'glass-ring-indigo-t1-s1', 'glass-ring-violet-t1', 'glass-ring-violet-t1-s1', 'glass-ring-orchid-t1', 'glass-ring-orchid-t1-s1', 'glass-ring-magenta-t1', 'glass-ring-magenta-t1-s1', 'glass-ring-rose-t1', 'glass-ring-rose-t1-s1', 'glass-ring-blush-t1', 'glass-ring-blush-t1-s1'],
    "Glass Ring t2": ['glass-ring-crimson-t2', 'glass-ring-crimson-t2-s1', 'glass-ring-coral-t2', 'glass-ring-coral-t2-s1', 'glass-ring-tangerine-t2', 'glass-ring-tangerine-t2-s1', 'glass-ring-amber-t2', 'glass-ring-amber-t2-s1', 'glass-ring-honey-t2', 'glass-ring-honey-t2-s1', 'glass-ring-citron-t2', 'glass-ring-citron-t2-s1', 'glass-ring-lime-t2', 'glass-ring-lime-t2-s1', 'glass-ring-jade-t2', 'glass-ring-jade-t2-s1', 'glass-ring-mint-t2', 'glass-ring-mint-t2-s1', 'glass-ring-aqua-t2', 'glass-ring-aqua-t2-s1', 'glass-ring-cyan-t2', 'glass-ring-cyan-t2-s1', 'glass-ring-sky-t2', 'glass-ring-sky-t2-s1', 'glass-ring-azure-t2', 'glass-ring-azure-t2-s1', 'glass-ring-cobalt-t2', 'glass-ring-cobalt-t2-s1', 'glass-ring-indigo-t2', 'glass-ring-indigo-t2-s1', 'glass-ring-violet-t2', 'glass-ring-violet-t2-s1', 'glass-ring-orchid-t2', 'glass-ring-orchid-t2-s1', 'glass-ring-magenta-t2', 'glass-ring-magenta-t2-s1', 'glass-ring-rose-t2', 'glass-ring-rose-t2-s1', 'glass-ring-blush-t2', 'glass-ring-blush-t2-s1'],
    "Glass Ring t3": ['glass-ring-crimson-t3', 'glass-ring-crimson-t3-s1', 'glass-ring-coral-t3', 'glass-ring-coral-t3-s1', 'glass-ring-tangerine-t3', 'glass-ring-tangerine-t3-s1', 'glass-ring-amber-t3', 'glass-ring-amber-t3-s1', 'glass-ring-honey-t3', 'glass-ring-honey-t3-s1', 'glass-ring-citron-t3', 'glass-ring-citron-t3-s1', 'glass-ring-lime-t3', 'glass-ring-lime-t3-s1', 'glass-ring-jade-t3', 'glass-ring-jade-t3-s1', 'glass-ring-mint-t3', 'glass-ring-mint-t3-s1', 'glass-ring-aqua-t3', 'glass-ring-aqua-t3-s1', 'glass-ring-cyan-t3', 'glass-ring-cyan-t3-s1', 'glass-ring-sky-t3', 'glass-ring-sky-t3-s1', 'glass-ring-azure-t3', 'glass-ring-azure-t3-s1', 'glass-ring-cobalt-t3', 'glass-ring-cobalt-t3-s1', 'glass-ring-indigo-t3', 'glass-ring-indigo-t3-s1', 'glass-ring-violet-t3', 'glass-ring-violet-t3-s1', 'glass-ring-orchid-t3', 'glass-ring-orchid-t3-s1', 'glass-ring-magenta-t3', 'glass-ring-magenta-t3-s1', 'glass-ring-rose-t3', 'glass-ring-rose-t3-s1', 'glass-ring-blush-t3', 'glass-ring-blush-t3-s1'],
    "Glass · Copper": ['copper-glow-disc', 'copper-glow-ring'],
    "Glass · Copper d1": ['copper-glow-disc-d1', 'copper-glow-ring-d1'],
    "Glass · Copper d2": ['copper-glow-disc-d2', 'copper-glow-ring-d2'],
    "Glass · Copper d3": ['copper-glow-disc-d3', 'copper-glow-ring-d3'],
    "Glass · Copper t1": ['copper-glow-disc-t1', 'copper-glow-disc-t1-s1', 'copper-glow-ring-t1', 'copper-glow-ring-t1-s1'],
    "Glass · Copper t2": ['copper-glow-disc-t2', 'copper-glow-disc-t2-s1', 'copper-glow-ring-t2', 'copper-glow-ring-t2-s1'],
    "Glass · Copper t3": ['copper-glow-disc-t3', 'copper-glow-disc-t3-s1', 'copper-glow-ring-t3', 'copper-glow-ring-t3-s1'],
    "Glass Pastel": ['glass-pastel-lavender', 'glass-pastel-mint', 'glass-pastel-peach', 'glass-pastel-sky', 'glass-pastel-lemon', 'glass-pastel-rose', 'glass-pastel-lilac', 'glass-pastel-aqua'],
    "Glass Pastel d1": ['glass-pastel-lavender-d1', 'glass-pastel-mint-d1', 'glass-pastel-peach-d1', 'glass-pastel-sky-d1', 'glass-pastel-lemon-d1', 'glass-pastel-rose-d1', 'glass-pastel-lilac-d1', 'glass-pastel-aqua-d1'],
    "Glass Pastel d2": ['glass-pastel-lavender-d2', 'glass-pastel-mint-d2', 'glass-pastel-peach-d2', 'glass-pastel-sky-d2', 'glass-pastel-lemon-d2', 'glass-pastel-rose-d2', 'glass-pastel-lilac-d2', 'glass-pastel-aqua-d2'],
    "Glass Pastel d3": ['glass-pastel-lavender-d3', 'glass-pastel-mint-d3', 'glass-pastel-peach-d3', 'glass-pastel-sky-d3', 'glass-pastel-lemon-d3', 'glass-pastel-rose-d3', 'glass-pastel-lilac-d3', 'glass-pastel-aqua-d3'],
    "Glass Pastel t1": ['glass-pastel-lavender-t1', 'glass-pastel-lavender-t1-s1', 'glass-pastel-mint-t1', 'glass-pastel-mint-t1-s1', 'glass-pastel-peach-t1', 'glass-pastel-peach-t1-s1', 'glass-pastel-sky-t1', 'glass-pastel-sky-t1-s1', 'glass-pastel-lemon-t1', 'glass-pastel-lemon-t1-s1', 'glass-pastel-rose-t1', 'glass-pastel-rose-t1-s1', 'glass-pastel-lilac-t1', 'glass-pastel-lilac-t1-s1', 'glass-pastel-aqua-t1', 'glass-pastel-aqua-t1-s1'],
    "Glass Pastel t2": ['glass-pastel-lavender-t2', 'glass-pastel-lavender-t2-s1', 'glass-pastel-mint-t2', 'glass-pastel-mint-t2-s1', 'glass-pastel-peach-t2', 'glass-pastel-peach-t2-s1', 'glass-pastel-sky-t2', 'glass-pastel-sky-t2-s1', 'glass-pastel-lemon-t2', 'glass-pastel-lemon-t2-s1', 'glass-pastel-rose-t2', 'glass-pastel-rose-t2-s1', 'glass-pastel-lilac-t2', 'glass-pastel-lilac-t2-s1', 'glass-pastel-aqua-t2', 'glass-pastel-aqua-t2-s1'],
    "Glass Pastel t3": ['glass-pastel-lavender-t3', 'glass-pastel-lavender-t3-s1', 'glass-pastel-mint-t3', 'glass-pastel-mint-t3-s1', 'glass-pastel-peach-t3', 'glass-pastel-peach-t3-s1', 'glass-pastel-sky-t3', 'glass-pastel-sky-t3-s1', 'glass-pastel-lemon-t3', 'glass-pastel-lemon-t3-s1', 'glass-pastel-rose-t3', 'glass-pastel-rose-t3-s1', 'glass-pastel-lilac-t3', 'glass-pastel-lilac-t3-s1', 'glass-pastel-aqua-t3', 'glass-pastel-aqua-t3-s1'],
    "Glass Pastel Ring": ['glass-pastel-lavender-ring', 'glass-pastel-mint-ring', 'glass-pastel-peach-ring', 'glass-pastel-sky-ring', 'glass-pastel-lemon-ring', 'glass-pastel-rose-ring', 'glass-pastel-lilac-ring', 'glass-pastel-aqua-ring'],
    "Glass Pastel Ring d1": ['glass-pastel-lavender-ring-d1', 'glass-pastel-mint-ring-d1', 'glass-pastel-peach-ring-d1', 'glass-pastel-sky-ring-d1', 'glass-pastel-lemon-ring-d1', 'glass-pastel-rose-ring-d1', 'glass-pastel-lilac-ring-d1', 'glass-pastel-aqua-ring-d1'],
    "Glass Pastel Ring d2": ['glass-pastel-lavender-ring-d2', 'glass-pastel-mint-ring-d2', 'glass-pastel-peach-ring-d2', 'glass-pastel-sky-ring-d2', 'glass-pastel-lemon-ring-d2', 'glass-pastel-rose-ring-d2', 'glass-pastel-lilac-ring-d2', 'glass-pastel-aqua-ring-d2'],
    "Glass Pastel Ring d3": ['glass-pastel-lavender-ring-d3', 'glass-pastel-mint-ring-d3', 'glass-pastel-peach-ring-d3', 'glass-pastel-sky-ring-d3', 'glass-pastel-lemon-ring-d3', 'glass-pastel-rose-ring-d3', 'glass-pastel-lilac-ring-d3', 'glass-pastel-aqua-ring-d3'],
    "Glass Pastel Ring t1": ['glass-pastel-lavender-ring-t1', 'glass-pastel-lavender-ring-t1-s1', 'glass-pastel-mint-ring-t1', 'glass-pastel-mint-ring-t1-s1', 'glass-pastel-peach-ring-t1', 'glass-pastel-peach-ring-t1-s1', 'glass-pastel-sky-ring-t1', 'glass-pastel-sky-ring-t1-s1', 'glass-pastel-lemon-ring-t1', 'glass-pastel-lemon-ring-t1-s1', 'glass-pastel-rose-ring-t1', 'glass-pastel-rose-ring-t1-s1', 'glass-pastel-lilac-ring-t1', 'glass-pastel-lilac-ring-t1-s1', 'glass-pastel-aqua-ring-t1', 'glass-pastel-aqua-ring-t1-s1'],
    "Glass Pastel Ring t2": ['glass-pastel-lavender-ring-t2', 'glass-pastel-lavender-ring-t2-s1', 'glass-pastel-mint-ring-t2', 'glass-pastel-mint-ring-t2-s1', 'glass-pastel-peach-ring-t2', 'glass-pastel-peach-ring-t2-s1', 'glass-pastel-sky-ring-t2', 'glass-pastel-sky-ring-t2-s1', 'glass-pastel-lemon-ring-t2', 'glass-pastel-lemon-ring-t2-s1', 'glass-pastel-rose-ring-t2', 'glass-pastel-rose-ring-t2-s1', 'glass-pastel-lilac-ring-t2', 'glass-pastel-lilac-ring-t2-s1', 'glass-pastel-aqua-ring-t2', 'glass-pastel-aqua-ring-t2-s1'],
    "Glass Pastel Ring t3": ['glass-pastel-lavender-ring-t3', 'glass-pastel-lavender-ring-t3-s1', 'glass-pastel-mint-ring-t3', 'glass-pastel-mint-ring-t3-s1', 'glass-pastel-peach-ring-t3', 'glass-pastel-peach-ring-t3-s1', 'glass-pastel-sky-ring-t3', 'glass-pastel-sky-ring-t3-s1', 'glass-pastel-lemon-ring-t3', 'glass-pastel-lemon-ring-t3-s1', 'glass-pastel-rose-ring-t3', 'glass-pastel-rose-ring-t3-s1', 'glass-pastel-lilac-ring-t3', 'glass-pastel-lilac-ring-t3-s1', 'glass-pastel-aqua-ring-t3', 'glass-pastel-aqua-ring-t3-s1'],
    "Glass Neon": ['glass-neon-magenta', 'glass-neon-lime', 'glass-neon-cyan', 'glass-neon-yellow', 'glass-neon-orange', 'glass-neon-purple', 'glass-neon-green', 'glass-neon-pink'],
    "Glass Neon d1": ['glass-neon-magenta-d1', 'glass-neon-lime-d1', 'glass-neon-cyan-d1', 'glass-neon-yellow-d1', 'glass-neon-orange-d1', 'glass-neon-purple-d1', 'glass-neon-green-d1', 'glass-neon-pink-d1'],
    "Glass Neon d2": ['glass-neon-magenta-d2', 'glass-neon-lime-d2', 'glass-neon-cyan-d2', 'glass-neon-yellow-d2', 'glass-neon-orange-d2', 'glass-neon-purple-d2', 'glass-neon-green-d2', 'glass-neon-pink-d2'],
    "Glass Neon d3": ['glass-neon-magenta-d3', 'glass-neon-lime-d3', 'glass-neon-cyan-d3', 'glass-neon-yellow-d3', 'glass-neon-orange-d3', 'glass-neon-purple-d3', 'glass-neon-green-d3', 'glass-neon-pink-d3'],
    "Glass Neon t1": ['glass-neon-magenta-t1', 'glass-neon-magenta-t1-s1', 'glass-neon-lime-t1', 'glass-neon-lime-t1-s1', 'glass-neon-cyan-t1', 'glass-neon-cyan-t1-s1', 'glass-neon-yellow-t1', 'glass-neon-yellow-t1-s1', 'glass-neon-orange-t1', 'glass-neon-orange-t1-s1', 'glass-neon-purple-t1', 'glass-neon-purple-t1-s1', 'glass-neon-green-t1', 'glass-neon-green-t1-s1', 'glass-neon-pink-t1', 'glass-neon-pink-t1-s1'],
    "Glass Neon t2": ['glass-neon-magenta-t2', 'glass-neon-magenta-t2-s1', 'glass-neon-lime-t2', 'glass-neon-lime-t2-s1', 'glass-neon-cyan-t2', 'glass-neon-cyan-t2-s1', 'glass-neon-yellow-t2', 'glass-neon-yellow-t2-s1', 'glass-neon-orange-t2', 'glass-neon-orange-t2-s1', 'glass-neon-purple-t2', 'glass-neon-purple-t2-s1', 'glass-neon-green-t2', 'glass-neon-green-t2-s1', 'glass-neon-pink-t2', 'glass-neon-pink-t2-s1'],
    "Glass Neon t3": ['glass-neon-magenta-t3', 'glass-neon-magenta-t3-s1', 'glass-neon-lime-t3', 'glass-neon-lime-t3-s1', 'glass-neon-cyan-t3', 'glass-neon-cyan-t3-s1', 'glass-neon-yellow-t3', 'glass-neon-yellow-t3-s1', 'glass-neon-orange-t3', 'glass-neon-orange-t3-s1', 'glass-neon-purple-t3', 'glass-neon-purple-t3-s1', 'glass-neon-green-t3', 'glass-neon-green-t3-s1', 'glass-neon-pink-t3', 'glass-neon-pink-t3-s1'],
    "Glass Neon Ring": ['glass-neon-magenta-ring', 'glass-neon-lime-ring', 'glass-neon-cyan-ring', 'glass-neon-yellow-ring', 'glass-neon-orange-ring', 'glass-neon-purple-ring', 'glass-neon-green-ring', 'glass-neon-pink-ring'],
    "Glass Neon Ring d1": ['glass-neon-magenta-ring-d1', 'glass-neon-lime-ring-d1', 'glass-neon-cyan-ring-d1', 'glass-neon-yellow-ring-d1', 'glass-neon-orange-ring-d1', 'glass-neon-purple-ring-d1', 'glass-neon-green-ring-d1', 'glass-neon-pink-ring-d1'],
    "Glass Neon Ring d2": ['glass-neon-magenta-ring-d2', 'glass-neon-lime-ring-d2', 'glass-neon-cyan-ring-d2', 'glass-neon-yellow-ring-d2', 'glass-neon-orange-ring-d2', 'glass-neon-purple-ring-d2', 'glass-neon-green-ring-d2', 'glass-neon-pink-ring-d2'],
    "Glass Neon Ring d3": ['glass-neon-magenta-ring-d3', 'glass-neon-lime-ring-d3', 'glass-neon-cyan-ring-d3', 'glass-neon-yellow-ring-d3', 'glass-neon-orange-ring-d3', 'glass-neon-purple-ring-d3', 'glass-neon-green-ring-d3', 'glass-neon-pink-ring-d3'],
    "Glass Neon Ring t1": ['glass-neon-magenta-ring-t1', 'glass-neon-magenta-ring-t1-s1', 'glass-neon-lime-ring-t1', 'glass-neon-lime-ring-t1-s1', 'glass-neon-cyan-ring-t1', 'glass-neon-cyan-ring-t1-s1', 'glass-neon-yellow-ring-t1', 'glass-neon-yellow-ring-t1-s1', 'glass-neon-orange-ring-t1', 'glass-neon-orange-ring-t1-s1', 'glass-neon-purple-ring-t1', 'glass-neon-purple-ring-t1-s1', 'glass-neon-green-ring-t1', 'glass-neon-green-ring-t1-s1', 'glass-neon-pink-ring-t1', 'glass-neon-pink-ring-t1-s1'],
    "Glass Neon Ring t2": ['glass-neon-magenta-ring-t2', 'glass-neon-magenta-ring-t2-s1', 'glass-neon-lime-ring-t2', 'glass-neon-lime-ring-t2-s1', 'glass-neon-cyan-ring-t2', 'glass-neon-cyan-ring-t2-s1', 'glass-neon-yellow-ring-t2', 'glass-neon-yellow-ring-t2-s1', 'glass-neon-orange-ring-t2', 'glass-neon-orange-ring-t2-s1', 'glass-neon-purple-ring-t2', 'glass-neon-purple-ring-t2-s1', 'glass-neon-green-ring-t2', 'glass-neon-green-ring-t2-s1', 'glass-neon-pink-ring-t2', 'glass-neon-pink-ring-t2-s1'],
    "Glass Neon Ring t3": ['glass-neon-magenta-ring-t3', 'glass-neon-magenta-ring-t3-s1', 'glass-neon-lime-ring-t3', 'glass-neon-lime-ring-t3-s1', 'glass-neon-cyan-ring-t3', 'glass-neon-cyan-ring-t3-s1', 'glass-neon-yellow-ring-t3', 'glass-neon-yellow-ring-t3-s1', 'glass-neon-orange-ring-t3', 'glass-neon-orange-ring-t3-s1', 'glass-neon-purple-ring-t3', 'glass-neon-purple-ring-t3-s1', 'glass-neon-green-ring-t3', 'glass-neon-green-ring-t3-s1', 'glass-neon-pink-ring-t3', 'glass-neon-pink-ring-t3-s1'],
    "Glass Mono": ['glass-mono-obsidian', 'glass-mono-charcoal', 'glass-mono-slate', 'glass-mono-silver', 'glass-mono-ivory', 'glass-mono-fog', 'glass-mono-ink', 'glass-mono-mist'],
    "Glass Mono d1": ['glass-mono-obsidian-d1', 'glass-mono-charcoal-d1', 'glass-mono-slate-d1', 'glass-mono-silver-d1', 'glass-mono-ivory-d1', 'glass-mono-fog-d1', 'glass-mono-ink-d1', 'glass-mono-mist-d1'],
    "Glass Mono d2": ['glass-mono-obsidian-d2', 'glass-mono-charcoal-d2', 'glass-mono-slate-d2', 'glass-mono-silver-d2', 'glass-mono-ivory-d2', 'glass-mono-fog-d2', 'glass-mono-ink-d2', 'glass-mono-mist-d2'],
    "Glass Mono d3": ['glass-mono-obsidian-d3', 'glass-mono-charcoal-d3', 'glass-mono-slate-d3', 'glass-mono-silver-d3', 'glass-mono-ivory-d3', 'glass-mono-fog-d3', 'glass-mono-ink-d3', 'glass-mono-mist-d3'],
    "Glass Mono t1": ['glass-mono-obsidian-t1', 'glass-mono-obsidian-t1-s1', 'glass-mono-charcoal-t1', 'glass-mono-charcoal-t1-s1', 'glass-mono-slate-t1', 'glass-mono-slate-t1-s1', 'glass-mono-silver-t1', 'glass-mono-silver-t1-s1', 'glass-mono-ivory-t1', 'glass-mono-ivory-t1-s1', 'glass-mono-fog-t1', 'glass-mono-fog-t1-s1', 'glass-mono-ink-t1', 'glass-mono-ink-t1-s1', 'glass-mono-mist-t1', 'glass-mono-mist-t1-s1'],
    "Glass Mono t2": ['glass-mono-obsidian-t2', 'glass-mono-obsidian-t2-s1', 'glass-mono-charcoal-t2', 'glass-mono-charcoal-t2-s1', 'glass-mono-slate-t2', 'glass-mono-slate-t2-s1', 'glass-mono-silver-t2', 'glass-mono-silver-t2-s1', 'glass-mono-ivory-t2', 'glass-mono-ivory-t2-s1', 'glass-mono-fog-t2', 'glass-mono-fog-t2-s1', 'glass-mono-ink-t2', 'glass-mono-ink-t2-s1', 'glass-mono-mist-t2', 'glass-mono-mist-t2-s1'],
    "Glass Mono t3": ['glass-mono-obsidian-t3', 'glass-mono-obsidian-t3-s1', 'glass-mono-charcoal-t3', 'glass-mono-charcoal-t3-s1', 'glass-mono-slate-t3', 'glass-mono-slate-t3-s1', 'glass-mono-silver-t3', 'glass-mono-silver-t3-s1', 'glass-mono-ivory-t3', 'glass-mono-ivory-t3-s1', 'glass-mono-fog-t3', 'glass-mono-fog-t3-s1', 'glass-mono-ink-t3', 'glass-mono-ink-t3-s1', 'glass-mono-mist-t3', 'glass-mono-mist-t3-s1'],
    "Glass Mono Ring": ['glass-mono-obsidian-ring', 'glass-mono-charcoal-ring', 'glass-mono-slate-ring', 'glass-mono-silver-ring', 'glass-mono-ivory-ring', 'glass-mono-fog-ring', 'glass-mono-ink-ring', 'glass-mono-mist-ring'],
    "Glass Mono Ring d1": ['glass-mono-obsidian-ring-d1', 'glass-mono-charcoal-ring-d1', 'glass-mono-slate-ring-d1', 'glass-mono-silver-ring-d1', 'glass-mono-ivory-ring-d1', 'glass-mono-fog-ring-d1', 'glass-mono-ink-ring-d1', 'glass-mono-mist-ring-d1'],
    "Glass Mono Ring d2": ['glass-mono-obsidian-ring-d2', 'glass-mono-charcoal-ring-d2', 'glass-mono-slate-ring-d2', 'glass-mono-silver-ring-d2', 'glass-mono-ivory-ring-d2', 'glass-mono-fog-ring-d2', 'glass-mono-ink-ring-d2', 'glass-mono-mist-ring-d2'],
    "Glass Mono Ring d3": ['glass-mono-obsidian-ring-d3', 'glass-mono-charcoal-ring-d3', 'glass-mono-slate-ring-d3', 'glass-mono-silver-ring-d3', 'glass-mono-ivory-ring-d3', 'glass-mono-fog-ring-d3', 'glass-mono-ink-ring-d3', 'glass-mono-mist-ring-d3'],
    "Glass Mono Ring t1": ['glass-mono-obsidian-ring-t1', 'glass-mono-obsidian-ring-t1-s1', 'glass-mono-charcoal-ring-t1', 'glass-mono-charcoal-ring-t1-s1', 'glass-mono-slate-ring-t1', 'glass-mono-slate-ring-t1-s1', 'glass-mono-silver-ring-t1', 'glass-mono-silver-ring-t1-s1', 'glass-mono-ivory-ring-t1', 'glass-mono-ivory-ring-t1-s1', 'glass-mono-fog-ring-t1', 'glass-mono-fog-ring-t1-s1', 'glass-mono-ink-ring-t1', 'glass-mono-ink-ring-t1-s1', 'glass-mono-mist-ring-t1', 'glass-mono-mist-ring-t1-s1'],
    "Glass Mono Ring t2": ['glass-mono-obsidian-ring-t2', 'glass-mono-obsidian-ring-t2-s1', 'glass-mono-charcoal-ring-t2', 'glass-mono-charcoal-ring-t2-s1', 'glass-mono-slate-ring-t2', 'glass-mono-slate-ring-t2-s1', 'glass-mono-silver-ring-t2', 'glass-mono-silver-ring-t2-s1', 'glass-mono-ivory-ring-t2', 'glass-mono-ivory-ring-t2-s1', 'glass-mono-fog-ring-t2', 'glass-mono-fog-ring-t2-s1', 'glass-mono-ink-ring-t2', 'glass-mono-ink-ring-t2-s1', 'glass-mono-mist-ring-t2', 'glass-mono-mist-ring-t2-s1'],
    "Glass Mono Ring t3": ['glass-mono-obsidian-ring-t3', 'glass-mono-obsidian-ring-t3-s1', 'glass-mono-charcoal-ring-t3', 'glass-mono-charcoal-ring-t3-s1', 'glass-mono-slate-ring-t3', 'glass-mono-slate-ring-t3-s1', 'glass-mono-silver-ring-t3', 'glass-mono-silver-ring-t3-s1', 'glass-mono-ivory-ring-t3', 'glass-mono-ivory-ring-t3-s1', 'glass-mono-fog-ring-t3', 'glass-mono-fog-ring-t3-s1', 'glass-mono-ink-ring-t3', 'glass-mono-ink-ring-t3-s1', 'glass-mono-mist-ring-t3', 'glass-mono-mist-ring-t3-s1'],
}


def main() -> int:
    for p in sorted(OUT_DIR.glob("enclave-icon-*-1024.png")):
        Image.open(p).convert("RGB").save(p, format="PNG")   # flatten alpha → opaque app-icon
    _make_grid()
    return 0


def _ordered() -> list[str]:
    listed = [v for vs in FAMILIES.values() for v in vs]
    extra = [p.name[len("enclave-icon-"):-len("-1024.png")]
             for p in sorted(OUT_DIR.glob("enclave-icon-*-1024.png"))]
    return listed + [v for v in extra if v not in listed]


def _make_grid() -> None:
    grid_path = OUT_DIR / "icon-grid.png"
    variants = _ordered()
    thumb, pad, label_h = 512, 16, 28
    cols = 5
    rows = (len(variants) + cols - 1) // cols
    grid_w = thumb * cols + pad * (cols + 1)
    grid_h = thumb * rows + pad * (rows + 1) + label_h * rows
    grid = Image.new("RGB", (grid_w, grid_h), BG)
    gd = ImageDraw.Draw(grid)
    font = None
    for fp in ["/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
               "/usr/share/fonts/TTF/DejaVuSans.ttf",
               "/usr/share/fonts/dejavu/DejaVuSans.ttf"]:
        if os.path.exists(fp):
            font = ImageFont.truetype(fp, 24); break
    font = font or ImageFont.load_default()
    for i, v in enumerate(variants):
        src = OUT_DIR / f"enclave-icon-{v}-1024.png"
        if not src.exists(): continue
        img = Image.open(src).convert("RGB").resize((thumb, thumb), Image.Resampling.LANCZOS)
        x = pad + (i % cols) * (thumb + pad)
        y = pad + (i // cols) * (thumb + pad + label_h)
        grid.paste(img, (x, y))
        fam = next((k for k, vs in FAMILIES.items() if v in vs), "More")
        label = f"{fam} · {v}"
        bbox = gd.textbbox((0, 0), label, font=font)
        gd.text((x + (thumb - (bbox[2] - bbox[0])) // 2, y + thumb + 4), label, fill=INK, font=font)
    grid.save(grid_path)


if __name__ == "__main__":
    sys.exit(main())
